name: Build and Deploy React App to Github Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install
    
    # Add Unit Test and then run them on the build
    # - name: Test
    #   run: npm run test

    - name: PreDeploy
      run: npm run predeploy
    
    - name: Deploy
      run: |
        git config --global user.name 'Jose'
        git config --global user.email 'kingjc232@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        npm run deploy